# Generated by Django 4.0.2 on 2022-02-17 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_picture_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='buyers',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
