# Generated by Django 4.0.2 on 2022-02-17 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_buyers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='buyers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='watchers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='watched_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
