# Generated by Django 4.0.2 on 2022-02-17 08:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_listing_watchers_listing_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\Portfolio\\Web Development\\cs50 web\\Project 3 (Commerce)\\Virtual\\commerce'), upload_to='images/'),
        ),
    ]
