# Generated by Django 4.0.3 on 2022-03-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_follower_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',)},
        ),
    ]
