# Generated by Django 4.0.3 on 2022-03-09 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_creator_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='userProfile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_user_followes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
